flags: {}
resolver: lts-8.5
packages:
- location: .
- location:
    git: git@github.com:timbod7/adl.git
    commit: 1980287757e1097f74ae57d170298c9fa7f3ccde
  subdirs:
  - haskell/utils
  - haskell/runtime
  - haskell/compiler-lib
  - haskell/compiler
  extra-dep: true
