flags: {}
resolver: lts-10.10
packages:
- location: .
- location:
    git: git@github.com:timbod7/adl.git
    commit: 8de6261e16e505385d2f9931a1007feb7991b760
  subdirs:
  - haskell/utils
  - haskell/runtime
  - haskell/compiler-lib
  - haskell/compiler
  extra-dep: true
