flags: {}
resolver: lts-10.10
packages:
- location: .
- location:
    git: git@github.com:timbod7/adl.git
    commit: 263bbd00e48c06d6ca957d2c9e872c12e4cde55d
  subdirs:
  - haskell/utils
  - haskell/runtime
  - haskell/compiler-lib
  - haskell/compiler
  extra-dep: true
